assetic:
    debug:          false
    use_controller: false
    read_from:      %kernel.root_dir%/../web
    write_to:       %kernel.root_dir%/../web
    filters:
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
    assets:
        jqueryfileupload_base_css:
            inputs:
                - bundles/jqueryfileupload/css/bootstrap/bootstrap.min.css
                - bundles/jqueryfileupload/css/bootstrap/bootstrap-responsive.min.css
                - bundles/jqueryfileupload/css/bootstrap/bootstrap-image-gallery.min.css
                - bundles/jqueryfileupload/css/jquery/jquery.fileupload-ui.css
            output: css/jqueryfileupload_base.min.css
            filters:
                - abs_cssrewrite
                - ?yui_css

        jqueryfileupload_noscript_css:
            inputs:
                - bundles/jqueryfileupload/css/jquery/jquery.fileupload-ui-noscript.css
            filters:
                - cssrewrite
                - ?yui_css

        jqueryfileupload_ie6_css:
            inputs:
                - bundles/jqueryfileupload/css/bootstrap/bootstrap-ie6.min.css
            filters:
                - cssrewrite
                - ?yui_css

        jqueryfileupload_base_js:
            inputs:
                - bundles/jqueryfileupload/js/jquery/jquery.min.js
                - bundles/jqueryfileupload/js/jquery/jquery.ui.widget.js
                - bundles/jqueryfileupload/js/tmpl.js
                - bundles/jqueryfileupload/js/load-image.min.js
                - bundles/jqueryfileupload/js/canvas-to-blob.min.js
                - bundles/jqueryfileupload/js/bootstrap/bootstrap.min.js
                - bundles/jqueryfileupload/js/bootstrap/bootstrap-image-gallery.min.js
                - bundles/jqueryfileupload/js/jquery/jquery.iframe-transport.js
                - bundles/jqueryfileupload/js/jquery/jquery.fileupload.js
                - bundles/jqueryfileupload/js/jquery/jquery.fileupload-fp.js
                - bundles/jqueryfileupload/js/jquery/jquery.fileupload-ui.js
                - bundles/jqueryfileupload/js/blueimpUploader.js
            filters:
                - ?yui_js

        jqueryfileupload_ie9_js:
            inputs:
                - bundles/jqueryfileupload/js/jquery/jquery.xdr-transport.js
            filters:
                - ?yui_js

