assetic:
    debug:          false
    use_controller: false
    read_from:      %kernel.root_dir%/../web
    write_to:       %kernel.root_dir%/../web
    filters:
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
    assets:
        jqueryfileupload_bootstrap_css:
            inputs:
                - 'bundles/jqueryfileupload/css/bootstrap/bootstrap.min.css'
                - 'bundles/jqueryfileupload/css/bootstrap/bootstrap-responsive.min.css'

        jqueryfileupload_blueimp_css:
            inputs:
                - 'bundles/jqueryfileupload/css/blueimp/bootstrap-image-gallery.min.css'
                - 'bundles/jqueryfileupload/css/blueimp/jquery.fileupload-ui.css'
    
        jqueryfileupload_base_css:
            inputs:
                - '@jqueryfileupload_bootstrap_css'
                - '@jqueryfileupload_blueimp_css'
            output: 'css/jqueryfileupload.min.css'
            filters:
                - abs_cssrewrite
                - ?yui_css

        jqueryfileupload_noscript_css:
            inputs:
                - 'bundles/jqueryfileupload/css/blueimp/jquery.fileupload-ui-noscript.css'
            filters:
                - abs_cssrewrite
                - ?yui_css

        jqueryfileupload_ie6_css:
            inputs:
                - 'bundles/jqueryfileupload/css/blueimp/bootstrap-ie6.min.css'
            filters:
                - abs_cssrewrite
                - ?yui_css
        
        jqueryfileupload_jquery_js:
            inputs:
                - 'bundles/jqueryfileupload/js/jquery/jquery.min.js'
        
        jqueryfileupload_bootstrap_js:
            inputs:
                - 'bundles/jqueryfileupload/js/bootstrap/bootstrap.min.js'
        
        jqueryfileupload_blueimp_js:
            inputs:
                - 'bundles/jqueryfileupload/js/blueimp/jquery.ui.widget.js'
                - 'bundles/jqueryfileupload/js/blueimp/tmpl.js'
                - 'bundles/jqueryfileupload/js/blueimp/load-image.min.js'
                - 'bundles/jqueryfileupload/js/blueimp/canvas-to-blob.min.js'
                - 'bundles/jqueryfileupload/js/blueimp/bootstrap-image-gallery.min.js'
                - 'bundles/jqueryfileupload/js/blueimp/jquery.iframe-transport.js'
                - 'bundles/jqueryfileupload/js/blueimp/jquery.fileupload.js'
                - 'bundles/jqueryfileupload/js/blueimp/jquery.fileupload-fp.js'
                - 'bundles/jqueryfileupload/js/blueimp/jquery.fileupload-ui.js'
                - 'bundles/jqueryfileupload/js/blueimp/blueimpUploader.js'

        jqueryfileupload_js:
            inputs:
                - '@jqueryfileupload_jquery_js'
                - '@jqueryfileupload_bootstrap_js'
                - '@jqueryfileupload_blueimp_js'
            output: 'js/jqueryfileupload.min.js'
            filters:
                - ?yui_js

        jqueryfileupload_ie9_js:
            inputs:
                - bundles/jqueryfileupload/js/blueimp/jquery.xdr-transport.js
            filters:
                - ?yui_js

