services:
    mylen.file_uploader:
        class: Mylen\JQueryFileUploadBundle\Services\FileUploader
        arguments: 
          - '%file_uploader.file_base_path%'
          - '%file_uploader.web_base_path%'
          - '%file_uploader.allowed_extensions%'
          - '%file_uploader.sizes%'
          - '%file_uploader.originals%'
        scope: container
