services:
    mylen.file_uploader:
        class: Mylen\JQueryFileUploadBundle\Services\FileUploader
        arguments: 
          - '%file_uploader.file_base_path%'
          - '%file_uploader.web_base_path%'
          - '@request'
          - '%file_uploader.allowed_extensions%'
          - '%file_uploader.sizes%'
          - '%file_uploader.originals%'
        scope: request

    # You usually won't need this sub-service directly,
    # however you can access it from a command, which is
    # convenient if you need to delete files relating to
    # something in a command context
    mylen.file_uploader_file_manager:
        class: Mylen\JQueryFileUploadBundle\Services\FileManager
        # class: Mylen\JQueryFileUploadBundle\Services\FileManager
        arguments: ['%file_uploader.file_base_path%']
          # For bc reasons we're not changing the names of the parameters
